package com.ejb.credit;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-03-18T21:39:02.774+01:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "CreditService", 
                  wsdlLocation = "http://127.0.0.1:8080/webservices-samples/CreditService/CreditCheckEndpointBean?WSDL",
                  targetNamespace = "http://localhost:8080/ejb/credit") 
public class CreditService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://localhost:8080/ejb/credit", "CreditService");
    public final static QName CreditCheckEndpointBeanPort = new QName("http://localhost:8080/ejb/credit", "CreditCheckEndpointBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/webservices-samples/CreditService/CreditCheckEndpointBean?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CreditService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/webservices-samples/CreditService/CreditCheckEndpointBean?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public CreditService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreditService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CreditService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CreditService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CreditService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CreditCheckEndpointBean
     */
    @WebEndpoint(name = "CreditCheckEndpointBeanPort")
    public CreditCheckEndpointBean getCreditCheckEndpointBeanPort() {
        return super.getPort(CreditCheckEndpointBeanPort, CreditCheckEndpointBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditCheckEndpointBean
     */
    @WebEndpoint(name = "CreditCheckEndpointBeanPort")
    public CreditCheckEndpointBean getCreditCheckEndpointBeanPort(WebServiceFeature... features) {
        return super.getPort(CreditCheckEndpointBeanPort, CreditCheckEndpointBean.class, features);
    }

}
