package com.ejb.credit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-03-18T21:39:02.746+01:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://localhost:8080/ejb/credit", name = "CreditCheckEndpointBean")
@XmlSeeAlso({ObjectFactory.class})
public interface CreditCheckEndpointBean {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "CreditCheck", targetNamespace = "http://localhost:8080/ejb/credit", className = "com.ejb.credit.CreditCheck")
    @WebMethod(operationName = "CreditCheck")
    @ResponseWrapper(localName = "CreditCheckResponse", targetNamespace = "http://localhost:8080/ejb/credit", className = "com.ejb.credit.CreditCheckResponse")
    public boolean creditCheck(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
